# Generated by Django 4.2.29 on 2026-07-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0028_schedule_share_token_schedulebookmark_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="club",
            name="club_combined_name",
        ),
        migrations.RemoveIndex(
            model_name="instructor",
            name="full_name_instructor",
        ),
        migrations.RemoveIndex(
            model_name="course",
            name="course_mnemonic_number",
        ),
    ]
