# Generated by Django 4.2.29 on 2026-07-03 16:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tcf_website", "0028_schedule_share_token_schedulebookmark_and_more"),
    ]

    operations = [
        # Drop the legacy Semester.season text column — the numeric `number`
        # field already encodes the season, so this column is redundant.
        migrations.RemoveField(
            model_name="semester",
            name="season",
        ),
    ]
